# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/klsa/lab2/lab2.cache/wt [current_project]
set_property parent.project_path D:/klsa/lab2/lab2.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
set_property ip_output_repo d:/klsa/lab2/lab2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/klsa/lab2/lab2.srcs/sources_1/new/inoutmoduleaa.v
  D:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/hdl/PS_system_wrapper.v
}
add_files D:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/PS_system.bd
set_property used_in_implementation false [get_files -all d:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/ip/PS_system_processing_system7_0_0/PS_system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/ip/PS_system_axi_gpio_0_0/PS_system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/ip/PS_system_axi_gpio_0_0/PS_system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/ip/PS_system_axi_gpio_0_0/PS_system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/ip/PS_system_axi_timer_0_0/PS_system_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/ip/PS_system_axi_timer_0_0/PS_system_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/ip/PS_system_rst_ps7_0_50M_0/PS_system_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/ip/PS_system_rst_ps7_0_50M_0/PS_system_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/ip/PS_system_rst_ps7_0_50M_0/PS_system_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/ip/PS_system_xbar_0/PS_system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/ip/PS_system_auto_pc_0/PS_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/PS_system_ooc.xdc]
set_property is_locked true [get_files D:/klsa/lab2/lab2.srcs/sources_1/bd/PS_system/PS_system.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/klsa/lab2/lab2.srcs/constrs_1/new/Lab2_Constaints1.xdc
set_property used_in_implementation false [get_files D:/klsa/lab2/lab2.srcs/constrs_1/new/Lab2_Constaints1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top PS_system_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef PS_system_wrapper.dcp

catch { report_utilization -file PS_system_wrapper_utilization_synth.rpt -pb PS_system_wrapper_utilization_synth.pb }
