set_property PACKAGE_PIN P17 [get_ports {leds[3]}]
set_property PACKAGE_PIN P18 [get_ports {leds[2]}]
set_property PACKAGE_PIN W10 [get_ports {leds[1]}]
set_property PACKAGE_PIN V7 [get_ports {leds[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {leds[0]}]
