# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.cache/wt [current_project]
set_property parent.project_path C:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
set_property ip_repo_paths c:/Users/grcomerce/Desktop/LAB6/ip_repo/Blink_1.0 [current_project]
set_property ip_output_repo c:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.srcs/sources_1/bd/tutorial_bd/hdl/tutorial_bd_wrapper.v
add_files C:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.srcs/sources_1/bd/tutorial_bd/tutorial_bd.bd
set_property used_in_implementation false [get_files -all c:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.srcs/sources_1/bd/tutorial_bd/ip/tutorial_bd_processing_system7_0_0/tutorial_bd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.srcs/sources_1/bd/tutorial_bd/ip/tutorial_bd_rst_ps7_0_50M_0/tutorial_bd_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.srcs/sources_1/bd/tutorial_bd/ip/tutorial_bd_rst_ps7_0_50M_0/tutorial_bd_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.srcs/sources_1/bd/tutorial_bd/ip/tutorial_bd_rst_ps7_0_50M_0/tutorial_bd_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.srcs/sources_1/bd/tutorial_bd/ip/tutorial_bd_auto_pc_0/tutorial_bd_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.srcs/sources_1/bd/tutorial_bd/tutorial_bd_ooc.xdc]
set_property is_locked true [get_files C:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.srcs/sources_1/bd/tutorial_bd/tutorial_bd.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/grcomerce/Desktop/LAB6/lab_6/lab_6.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top tutorial_bd_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef tutorial_bd_wrapper.dcp

catch { report_utilization -file tutorial_bd_wrapper_utilization_synth.rpt -pb tutorial_bd_wrapper_utilization_synth.pb }
